config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do


  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  get 'customers/withdrawal' => 'customers#withdrawal'
  patch 'customers/withdrawal' => 'customers#withdrawal'
  post 'homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'customer/sessions#new_guest'
  end
    resources :customers, only: [:show, :edit, :update, :index]
    resources :contributions, only: [:new, :create, :show, :index, :edit, :update, :destroy]
    resources :shops, only: [:index, :show] do
      resources :contributions, only: [:new]
    end

end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :index, :destroy, :edit, :update]
    resources :contributions, only: [:index, :destroy]
    resources :shops, only: [:new, :create, :show, :index, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  validates :title, :tag_name, :star, :comment,
  presence: true
  belongs_to :shop, optional: true
  belongs_to :customer
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [200, 200]).processed
  end

   def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_contribution_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_contribution_tag
    end
   end

end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < ApplicationController

  def index
    @contributions = Contribution.all
  end

  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to admin_contributions_path
  end

  private

  def  contribution_params
    params.require(:contribution).permit(:customer_id, :menu_id, :title, :star, :comment, :image)
  end

end

app/helpers/admin/contribution_helper.rb
module Admin::ContributionHelper
end

app/views/admin/contributions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿一覧</h1>
      <table>
        <% @contributions.each do |contribution| %>
        <thead>
          <tr>
            <td>投稿者<%= contribution.customer.name %><br>タイトル <%= contribution.title %></td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag contribution.get_image %>
              コメント <%= contribution.comment %>
               <%= link_to '取り消し', admin_contribution_path(contribution.id), method: :delete, class: "btn btn-danger btn-sm btn-block sign_up"%>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>