config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do


  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  get 'customers/withdrawal' => 'customers#withdrawal'
  patch 'customers/withdrawal' => 'customers#withdrawal'
  post 'homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'customer/sessions#new_guest'
  end
    resources :customers, only: [:show, :edit, :update, :index]
    resources :contributions, only: [:new, :create, :show, :index, :edit, :update, :destroy]
    resources :shops, only: [:index, :show] do
      resources :contributions, only: [:new]
    end

end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :index, :destroy, :edit, :update]
    resources :contributions, only: [:index, :destroy]
    resources :shops, only: [:new, :create, :show, :index, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>管理者ホーム</h1>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>ラーメンMap運営ページ</h1>
      <%= link_to "管理運営", new_admin_session_path, class: "btn btn-info btn-sm btn-block sign_up" %>
    </div>
  </div>
</div>