config/routes.rb
Rails.application.routes.draw do
root to: 'public/homes#top'

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

namespace :public do


  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  get 'customers/withdrawal' => 'customers#withdrawal'
  patch 'customers/withdrawal' => 'customers#withdrawal'
  post 'homes/guest_sign_in', to: 'homes#new_guest'
  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'customer/sessions#new_guest'
  end
    resources :customers, only: [:show, :edit, :update, :index]
    resources :contributions, only: [:new, :create, :show, :index, :edit, :update, :destroy]
    resources :shops, only: [:index, :show] do
      resources :contributions, only: [:new]
    end

end

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
  get 'homes/top' => 'homes#top'
  get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :index, :destroy, :edit, :update]
    resources :contributions, only: [:index, :destroy]
    resources :shops, only: [:new, :create, :show, :index, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :shop
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  validates :title, :tag_name, :star, :comment,
  presence: true
  belongs_to :shop, optional: true
  belongs_to :customer
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [200, 200]).processed
  end

   def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_contribution_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_contribution_tag
    end
   end

end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :birthday, :email, :password,
  presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
   end
  end

  has_many :contribution, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :contributions

  geocoded_by :address
  has_one_attached :image

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [200, 200]).processed
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :contributions, through: :tagmaps
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :contribution
  belongs_to :tag
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_customers_path
  end

  private

  def  customer_params
    params.require(:customer).permit(:email, :name, :birthday, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
   def after_sign_out_path_for(resource)
    admin_homes_top_path
   end

   def after_sign_in_path_for(resource)
    admin_homes_about_path
   end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to admin_homes_about_path
    else
      redirect_to new_admin_shop_path
    end
  end

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    flash[:notice] = "削除しました"
    redirect_to admin_shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:menu_name, :menu_introduction, :price, :name, :introduction, :telephone_number, :email, :image, :latitude, :longitude, :address)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:birthday, :name])
  end
end

app/helpers/admin/contribution_helper.rb
module Admin::ContributionHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menu_helper.rb
module Admin::MenuHelper
end

app/helpers/admin/shop_helper.rb
module Admin::ShopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ramenMap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-light green">
        <div class="container">
          <h1>ラーメンMap</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <%= button_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-danger " %>
                <%= link_to admin_customers_path, class: 'nav-link text-dark' do%>
                  <p>一覧</p>
                <% end %>
                <%= link_to admin_contributions_path, class: 'nav-link text-dark' do%>
                  <p>投稿</p>
                <% end %>
                <%= link_to new_admin_shop_path, class: 'nav-link text-dark' do%>
                  <p>ショップ</p>
                <% end %>
              <% elsif customer_signed_in? %>
                <% if current_customer.email == "guest@example.com"%>
                 <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do%>
                    <p>ログアウト</p>
                  <% end %>
                  <%= link_to public_contributions_path, class: 'nav-link text-dark' do%>
                    <P>投稿一覧</P>
                  <% end %>
                <%else%>
                  <%= link_to public_shops_path, class: 'nav-link text-dark' do%>
                    <p>店舗一覧</p>
                  <% end %>
                  <%= link_to public_customer_path(current_customer.id), class: 'nav-link text-dark' do%>
                    <p>マイページ</p>
                  <% end %>
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' do%>
                    <p>ログアウト</p>
                  <% end %>
                  <%= link_to public_contributions_path, class: 'nav-link text-dark' do%>
                    <P>投稿一覧</P>
                  <% end %>
                <%end%>

              <% else %>
                <%= link_to public_homes_guest_sign_in_path, method: :post, class: 'nav-link text-dark' do%>
                <p>ゲストログイン</p>
                <% end %>
                <%= link_to public_contributions_path, class: 'nav-link text-dark' do%>
                <P>投稿一覧</P>
                <% end %>
              <% end %>
    </header>
    <main class="mb-auto">
      <%= flash[:notice]  %>
    <%= yield %>
    </main>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV["GOOGLE_API_KEY"]%>&callback=initMap"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js"></script>
  </body>
</html>